### ISSUE TITLE
decode metric histories for integration tests

### ISSUE THREAD

**Issue by suprjinx** [G-Research/fasttrackml#639] opened 2023-11-22 18:39 UTC
the binary encoding of metric histories has left some gaps in our integration tests -- need to decode and verify.

https://github.com/G-Research/fasttrackml/blob/main/tests/integration/golang/mlflow/metric/get_histories_test.go#L126-L128

**Comment by jgiannuzzi** [comment] 2023-11-24 14:38
duplicate of #226

**Closed by jgiannuzzi** 2023-11-24 14:38 UTC
