### ISSUE TITLE
MLFlow python client: add context to `GetMetricHistory` (?) and `GetMetricHistories`

### ISSUE THREAD

**Issue by suprjinx** [G-Research/fasttrackml#671] opened 2023-12-01 14:39 UTC
`GetMetricHistories` accepts a json body from a post, so adding context is pretty easy -- `GetMetricHistory` is GET with url params only, and map params are not supported.

Outstanding question: how is context represented here? stringified json? or json sub object at key 'context'

**Comment by suprjinx** [comment] 2023-12-18 16:26
![Image](https://github.com/G-Research/fasttrackml/assets/1463452/7f50e8ad-87d4-4852-8030-b3210719c61d)

verified in `batch.py` with the code above -- but I think this should be added to the FasttrackML client

**Comment by jgiannuzzi** [comment] 2024-01-08 14:50
duplicate of #363

**Closed by jgiannuzzi** 2024-01-08 14:50 UTC
