### ISSUE TITLE
Find a style guide that closely matches our current patterns and import it into the repo

### ISSUE THREAD

**Issue by dave-gantenbein** [G-Research/fasttrackml#156] opened 2023-07-06 13:47 UTC
Current and future contributors should not need to guess at our coding style patterns. Find an extant golang style guide that looks like what we currently do and import it. This is for documentation purposes only, and will eventually guide our linter implementation.

**Comment by jgiannuzzi** [comment] 2023-07-06 14:07
Do you mean formatting guidelines like implemented in https://github.com/G-Research/fasttrackml/pull/155? Or is this more about structure?

**Comment by jgiannuzzi** [comment] 2023-07-10 10:46
We could probably start with making our `golangci-lint` thing work on the entire codebase.

**Comment by jgiannuzzi** [comment] 2023-09-11 13:44
partial duplicate of #213

**Closed by jgiannuzzi** 2023-09-11 13:44 UTC
