### ISSUE TITLE
Group Mean is not displayed correctly

### ISSUE THREAD

**Issue by Kotwic4** [G-Research/fasttrackml#267] opened 2023-08-21 11:32 UTC
I tried to use group statistics, but the data I got are not correct. All my values are integers, but in the charts values become some strange float values.

Steps to reproduce:

1. Generate data
```
    mlflow.set_experiment("/TestMultipleScores")
    for i in range(5):
        for model in ["A", "B"]:
            with mlflow.start_run():
                mlflow.log_params({"model": model, "try": i})
                model_score = 100 if model == "A" else 500
                model_score += i
                mlflow.log_metric("model_score", model_score)
                mlflow.log_metric("model_score", model_score + 1)
                mlflow.log_metric("model_score", model_score + 2)
```
2. Got to metric ui and specify score as metric, group by model
![image](https://github.com/G-Research/fasttrackml/assets/10147099/7aed7b72-f664-40a2-aa2c-9e60c02f213a)
As you can see Group values are not calculated properly

**Comment by jescalada** [comment] 2024-06-05 21:11
The main bug here was solved upstream, however, there seems to be another issue that I noticed when running the test script provided. The Mean value is no longer being calculated:

![Image](https://github.com/G-Research/fasttrackml/assets/97265671/ed00942d-a22d-479c-a66e-82527c39c287)

This is a different problem from https://github.com/G-Research/fasttrackml/issues/266, although they may be related. I renamed this issue for ease of tracking.

**Comment by jescalada** [comment] 2024-07-24 03:54
@Kotwic4 

I've spent some time diagnosing the issue with the upstream repo, and it seems that Aim v3.17.5 is working without any bug. It appears that something we did while forking may have introduced this issue between June (when 3.17.5 was released) and August 2023.

Unfortunately, I was not able to reproduce the specific issue with the Group Min and Group Max showing Mean ± SD. The only problem I found is that the Mean/Median column values disappear when someone hovers on a table row or the chart. However, they do populate correctly when switching the option from the Select Aggregation Method popover (from the options arrow in the Aggregate Metrics button).

I've spent considerable time looking for a fix for the Mean/Median column issue without much luck. My best guess is that the column gets overridden with blank values when the tooltip shows up due to some React re-rendering issue. Given the complexity and time it would take to resolve it, we decided to classify this issue as "won't fix."

Thank you for your understanding. Please feel free to reach out to us if you have any other issues, or info related to this issue.

**Closed** 2024-07-24 03:54 UTC
Labels: wontfix, ui
